cabal-version: 3.0
name: haskell-trials
version: 0.1.0.0
license: MIT
license-file: LICENSE
author: ibonny
maintainer: ibonny@gmail.com
build-type: Simple
extra-doc-files: CHANGELOG.md

common warnings
  ghc-options: -Wall

executable haskell-trials
  import: warnings
  main-is: Main.hs
  build-depends: base ^>=4.18.3.0
  hs-source-dirs: app
  default-language: Haskell2010

executable first
  hs-source-dirs: .
  main-is: first.hs
  hs-source-dirs: app
  default-language: Haskell2010
  build-depends: base >=4.7 && <5
  ghc-options:
    -Wall
    -Wcompat
    -Widentities
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wmissing-export-lists
    -Wmissing-home-modules
    -Wpartial-fields
    -Wredundant-constraints

executable second
  hs-source-dirs: .
  main-is: second.hs
  hs-source-dirs: app
  default-language: Haskell2010
  build-depends:
    aeson >=2.2.3.0,
    base >=4.7 && <5,
    http-client,
    http-client-tls,

  ghc-options:
    -Wall
    -Wcompat
    -Widentities
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wmissing-export-lists
    -Wmissing-home-modules
    -Wpartial-fields
    -Wredundant-constraints

executable third
  hs-source-dirs: .
  main-is: third.hs
  hs-source-dirs: app
  default-language: Haskell2010
  build-depends: base >=4.7 && <5
  ghc-options:
    -Wall
    -Wcompat
    -Widentities
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wmissing-export-lists
    -Wmissing-home-modules
    -Wpartial-fields
    -Wredundant-constraints

executable fourth
  main-is: fourth.hs
  hs-source-dirs: app
  default-language: Haskell2010
  build-depends:
    base >=4.7 && <5,
    bytestring,
    http-conduit,

  ghc-options:
    -Wall
    -Wcompat
    -Widentities
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wmissing-export-lists
    -Wmissing-home-modules
    -Wpartial-fields
    -Wredundant-constraints

executable monadic-test
  main-is: monadic-test.hs
  hs-source-dirs: app
  default-language: Haskell2010
  build-depends:
    base >=4.7 && <5,
    bytestring >=0.11.5.4,
    http-conduit >=2.3.9.1,

  ghc-options:
    -Wall
    -Wcompat
    -Widentities
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wmissing-export-lists
    -Wmissing-home-modules
    -Wpartial-fields
    -Wredundant-constraints

executable rosalind_splc
  main-is: rosalind_splc.hs
  hs-source-dirs: app
  default-language: Haskell2010
  build-depends:
    base >=4.7 && <5,
    text,

  ghc-options:
    -Wall
    -Wcompat
    -Widentities
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wmissing-export-lists
    -Wmissing-home-modules
    -Wpartial-fields
    -Wredundant-constraints

executable rosalind_lgis
  main-is: rosalind_lgis.hs
  hs-source-dirs: app
  default-language: Haskell2010
  build-depends:
    base >=4.7 && <5,
    split,
    text,

  ghc-options:
    -Wall
    -Wcompat
    -Widentities
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wmissing-export-lists
    -Wmissing-home-modules
    -Wpartial-fields
    -Wredundant-constraints

executable rosalind_pmch
  main-is: rosalind_pmch.hs
  hs-source-dirs: app
  default-language: Haskell2010
  build-depends: base >=4.7 && <5
  ghc-options:
    -Wall
    -Wcompat
    -Widentities
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wmissing-export-lists
    -Wmissing-home-modules
    -Wpartial-fields
    -Wredundant-constraints

executable rosalind_pper
  main-is: rosalind_pper.hs
  hs-source-dirs: app
  default-language: Haskell2010
  build-depends: base >=4.7 && <5
  ghc-options:
    -Wall
    -Wcompat
    -Widentities
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wmissing-export-lists
    -Wmissing-home-modules
    -Wpartial-fields
    -Wredundant-constraints

executable rosalind_prob
  main-is: rosalind_prob.hs
  hs-source-dirs: app
  default-language: Haskell2010
  build-depends:
    base >=4.7 && <5,
    split,
    text,

  ghc-options:
    -Wall
    -Wcompat
    -Widentities
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wmissing-export-lists
    -Wmissing-home-modules
    -Wpartial-fields
    -Wredundant-constraints

executable rosalind_sign
  main-is: rosalind_sign.hs
  hs-source-dirs: app
  default-language: Haskell2010
  build-depends:
    base >=4.7 && <5,
    text,

  ghc-options:
    -Wall
    -Wcompat
    -Widentities
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wmissing-export-lists
    -Wmissing-home-modules
    -Wpartial-fields
    -Wredundant-constraints

executable rosalind_sseq
  main-is: rosalind_sseq.hs
  hs-source-dirs: app
  default-language: Haskell2010
  build-depends: base >=4.7 && <5
  ghc-options:
    -Wall
    -Wcompat
    -Widentities
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wmissing-export-lists
    -Wmissing-home-modules
    -Wpartial-fields
    -Wredundant-constraints

executable rosalind_tran
  main-is: rosalind_tran.hs
  hs-source-dirs: app
  default-language: Haskell2010
  build-depends:
    base >=4.7 && <5,
    split,

  ghc-options:
    -Wall
    -Wcompat
    -Widentities
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wmissing-export-lists
    -Wmissing-home-modules
    -Wpartial-fields
    -Wredundant-constraints
